# Generated by Django 3.1.5 on 2021-04-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billingprofile_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='customer_id',
        ),
    ]
