# Generated by Django 3.1.5 on 2021-04-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_timestamp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
