# Generated by Django 3.1.5 on 2021-04-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210404_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('shipped', 'shipped'), ('refunded', 'refunded')], default='created', max_length=120),
        ),
    ]
